# Generated by Django 2.0.6 on 2018-06-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_page',
            field=models.TextField(blank=True, verbose_name='страница продукта'),
        ),
    ]
